logging:
  config: classpath:logback-${spring.profiles.active}.xml

spring:
  datasource:
    hikari:
      connection-test-query: SELECT 1
      allow-pool-suspension: true
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    hibernate:
      use-new-id-generator-mappings: false

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    
---
spring:
  profiles: dev
  datasource:
    hikari:
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbc-url: jdbc:log4jdbc:mysql://localhost:3306/studydb?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
      username: 
      password: 
  thymeleaf:
    cache: false
  resources:
    cache:
      period: 0
  cloud:
    config:
      uri : 
      name : 
    

---
spring:
  profiles: production
  datasource:
    hikari:
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbc-url: jdbc:log4jdbc:mysql://localhost:3306/studydb?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
      username: 
      password: 